Add an optional commitHash filter
alextompkins/download-prior-artifact pull request #20
Opened 2022-07-22 20:20 UTC by james-perfectserve

I like your code, much cleaner than some of the other options I looked through.

For my use case I need the additional option of filtering the artifacts to ones that are tied to a commit hash before matching on name.

fyi, before I touched anything I wasn't able to run `npm ci` something to do with an eslint peer dependency.
I tried installing using pnpm instead of npm and that let me get past the error. Lint isn't part of my normal tool chain, so I didn't spend any time trying to fix it.

2022-07-22 22:11 UTC, alextompkins commented
Thanks for the contribution @james-perfectserve. I'm not sure what the issue was with `npm ci` - I tried it on main and had no issues, but I've bumped all the dependencies on main anyway.

2022-07-22 22:34 UTC, alextompkins requested changes

2022-07-22 22:34 UTC, alextompkins commented on src/action.ts
> +  commitHash: string
I realise github will pass in an empty string if this is not provided, but we should make this clearer by marking it as optional.

2022-07-22 22:34 UTC, alextompkins commented on src/action.ts
> +    commitHash: core.getInput('commitHash', { required: false }),
Once we mark `commitHash` as optional, we can set it up by doing 
```ts
commitHash: core.getInput('commitHash', { required: false }) || undefined
```

2022-07-22 22:34 UTC, alextompkins commented on src/main.ts
> +        artifact.workflow_run?.head_sha?.startsWith(commitHash)
Looks like `octokit`'s type definitions for this response are incomplete. Can we patch the definition with a `.d.ts` file?

2022-07-22 22:35 UTC, alextompkins commented on pnpm-lock.yaml
> +lockfileVersion: 5.4
Please remove the pnpm-lock.yaml, we only want one lockfile in this repo.

2022-07-24 19:29 UTC, james-perfectserve commented
> Thanks for the contribution @james-perfectserve. I'm not sure what the issue was with `npm ci` - I tried it on main and had no issues, but I've bumped all the dependencies anyway.

That fixed it, I can run npm ci now

2022-07-24 19:31 UTC, james-perfectserve commented on src/main.ts
> +        artifact.workflow_run?.head_sha?.startsWith(commitHash)
I created a d.ts file to temporarily address the issue. Also raised an issue for them https://github.com/actions/toolkit/issues/1137

2022-07-25 13:40 UTC, james-perfectserve commented on src/action.ts
> +    commitHash: core.getInput('commitHash', { required: false }),
done

2022-07-25 13:40 UTC, james-perfectserve commented on src/action.ts
> +  commitHash: string
I updated it to `commitHash?: string`

2022-07-26 12:05 UTC, alextompkins commented on src/main.ts
> +        artifact.workflow_run?.head_sha?.startsWith(commitHash)
Thanks for raising the issue :)

2022-07-26 12:05 UTC, alextompkins approved these changes

2022-07-26 12:07 UTC, merged

2022-07-26 12:14 UTC, alextompkins commented
I've merged and just released [v1.1.0](https://github.com/alextompkins/download-prior-artifact/releases/tag/v1.1.0). Let me know how that goes for you @james-perfectserve

2022-07-26 12:15 UTC, alextompkins commented
I'll update the README too when I get a chance...